spring:
  application:
    name: server
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.settings.trace: true
    console.path: /h2-console
    
grpc:
  server:
    port: 9898
